export const WeatherActionTypes = {
    SET_CURRENT_WEATHER: 'SET_CURRENT_WEATHER',
    SET_FIVE_DAY_FORECAST: 'SET_FIVE_DAY_FORECAST',
    SET_CURRENT_CITY_KEY: 'SET_CURRENT_CITY_KEY',
    FETCH_CURRENT_WEATHER_START: 'FETCH_CURRENT_WEATHER_START',
    FETCH_CURRENT_WEATHER_SUCCESS: 'FETCH_CURRENT_WEATHER_SUCCESS',
    FETCH_CURRENT_WEATHER_FAILURE: 'FETCH_CURRENT_WEATHER_FAILURE',
    FETCH_FORECAST_START: 'FETCH_FORECAST_START',
    FETCH_FORECAST_SUCCESS: 'FETCH_FORECAST_SUCCESS',
    FETCH_FORECAST_FAILURE: 'FETCH_FORECAST_FAILURE',
}