export const AutocompleteActionTypes = {
    FETCH_AUTOCOMPLETE_START: 'FETCH_AUTOCOMPLETE_START',
    FETCH_AUTOCOMPLETE_SUCCESS: 'FETCH_AUTOCOMPLETE_SUCCESS',
    FETCH_AUTOCOMPLETE_FAILURE: 'FETCH_AUTOCOMPLETE_FAILURE',
    FETCH_SEARCH_QUERY: 'FETCH_SEARCH_QUERY',
    CHECK_MATCH_INPUT: 'CHECK_MATCH_INPUT'
}